---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^10\\s*\\>\\s*9\\s*$"
  - "^11\\s*\\>\\=\\s*11\\s*$"
  - "^87\\s*\\< \\s*7\\s*$"
  - "^87\\s*\\<\\=\\s*100\\s*$"
  - "^9\\s*\\=\\=\\s*9\\s*$"
  - "^8\\s*\\!\\=\\s*8\\s*$"
name: No todo es un número
