---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^len\\s*\\(\\s*\\'prosopopeya\\'\\s*\\)\\s*$"
  - ^len\s*\(\s*\"Buenos días a todo el mundo\"\s*\)\s*$
  - "^len\\s*\\(\\s*\\'¿No tenés 5 minutos\\?\\'\\s*\\)\\s*$"
name: "¿Cuánto mide?"
