---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - ^str\.startswith\s*\(\s*\"Fundación e imperio\"\s*\,\s*\"Fundación\"\s*\)\s*$
  - ^str\.endswith\s*\(\s*\"Bueno, y sí\"\s*\,\s*\"y sí\"\s*\)\s*$
  - ^str\.endswith\s*\(\s*\"Hola, ¿qué tal?\"\s*\,\s*\"Hola\"\s*\)\s*$
name: De principio a fin
