---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - 2\s*\*\s*3\s*
  - 8\s*\+\s*7\s*
  - 21\s*\/\s*7\s*
  - 11\s*\-\s*2\s*
name: Calculo que sí
