---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^5\\s*\\+\\s*6\\s*$"
  - ^5\s*\=\=\s*\"5\"\s*$
  - "^8\\s*\\>\\s*6\\s*$"
  - "^False\\s*\\/\\s*True\\s*$"
  - "^\\'hola\\'\\s+or\\s+\\'chau\\'\\s*$"
name: Operando con sentido
