---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - ^\"amor\"\s+in\s+\"celos\"\s*$
  - ^\"placer\"\s+in\s+\"dolor\"\s*$
  - ^\"historia\"\s+in\s+\"prehistoria\"\s*$
name: Yo soy parte
