---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - '"guarda"\s*+\s*"polvos"\s*'
  - '"Hola, "\s*+\s*"¿cómo estás\?"\s*'
  - '"Dame "\s*+\s*str\(5\)\s*'
  - "'Mari'\\s*+\\s*'posa'\\s*"
name: Palabras, solo palabras
